license="${mod_license}"

issueTrackerURL="https://github.com/Footdablit2310/FootLib/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

authors="Footdablit2310"

description='''
This Mod adds RCC system and utils
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

# Minecraft
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# FootDiscordMC
[[dependencies.${mod_id}]]
modId="footdiscordmc"
type="optional"
versionRange="*"
ordering="NONE"
side="SERVER"

